BT1

In [1]:
import torch
import numpy as np
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")
# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")
# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.4779, 0.9022],
        [0.1282, 0.7150]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


In [2]:
import torch

# Dữ liệu gốc
x_data = torch.tensor([[1, 2],
                       [3, 4]])

# 1️⃣ Cộng x_data với chính nó
add_result = x_data + x_data
print("1. Kết quả cộng x_data với chính nó:\n", add_result, "\n")

# 2️⃣ Nhân x_data với 5 (nhân vô hướng)
mul_scalar_result = x_data * 5
print("2. Kết quả nhân x_data với 5:\n", mul_scalar_result, "\n")

# 3️⃣ Nhân ma trận x_data với ma trận chuyển vị của nó
matmul_result = x_data @ x_data.T   # hoặc torch.matmul(x_data, x_data.T)
print("3. Kết quả nhân ma trận x_data với x_data.T:\n", matmul_result)


1. Kết quả cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]]) 

2. Kết quả nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]]) 

3. Kết quả nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])


In [3]:
import torch

# Dữ liệu gốc
x_data = torch.tensor([[1, 2],
                       [3, 4]])

# 1️⃣ Lấy ra hàng đầu tiên
first_row = x_data[0]
print("1. Hàng đầu tiên:\n", first_row, "\n")

# 2️⃣ Lấy ra cột thứ hai
second_col = x_data[:, 1]
print("2. Cột thứ hai:\n", second_col, "\n")

# 3️⃣ Lấy ra giá trị ở hàng thứ hai, cột thứ hai
value_2_2 = x_data[1, 1]
print("3. Giá trị tại hàng 2, cột 2:", value_2_2)


1. Hàng đầu tiên:
 tensor([1, 2]) 

2. Cột thứ hai:
 tensor([2, 4]) 

3. Giá trị tại hàng 2, cột 2: tensor(4)


In [4]:
import torch

# 1️⃣ Tạo tensor ngẫu nhiên có shape (4, 4)
x = torch.rand(4, 4)
print("Tensor ban đầu (shape = 4x4):\n", x, "\n")

# 2️⃣ Thay đổi shape thành (16, 1)
x_reshaped = x.view(16, 1)   # hoặc x.reshape(16, 1)
print("Tensor sau khi reshape (shape = 16x1):\n", x_reshaped)


Tensor ban đầu (shape = 4x4):
 tensor([[0.5158, 0.4139, 0.1169, 0.3309],
        [0.8658, 0.5331, 0.0135, 0.7376],
        [0.7384, 0.6431, 0.4340, 0.6484],
        [0.2765, 0.8152, 0.7048, 0.8243]]) 

Tensor sau khi reshape (shape = 16x1):
 tensor([[0.5158],
        [0.4139],
        [0.1169],
        [0.3309],
        [0.8658],
        [0.5331],
        [0.0135],
        [0.7376],
        [0.7384],
        [0.6431],
        [0.4340],
        [0.6484],
        [0.2765],
        [0.8152],
        [0.7048],
        [0.8243]])


BT2

In [5]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")
# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")
# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")
# Thực hiện thêm các phép toán
z = y * y * 3
# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))
# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x7e8e815ac730>
Đạo hàm của z theo x: tensor([18.])


Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?

Trả lời: PyTorch báo lỗi

RuntimeError: Trying to backward through the graph a second time,
but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

Lí do: Khi thực hiện:

z.backward()


PyTorch sẽ:

1. Tính toán đạo hàm của z theo x.

2. Giải phóng biểu đồ tính toán (computation graph) để tiết kiệm bộ nhớ, vì mặc định PyTorch giả định bạn chỉ cần lan truyền ngược một lần.

BT3

In [7]:
# Lớp nn.Linear thực hiện một phép biến đổi tuyến tính y = xA^T + b.
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 1.0374,  0.0094],
        [ 0.5180, -0.6498],
        [ 0.1681, -0.1376]], grad_fn=<AddmmBackward0>)


In [8]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])
# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 7.1055e-02, -9.1139e-01, -3.8730e-01],
        [-4.2769e-01, -3.1663e-01,  2.6887e-01],
        [ 1.4158e-03,  1.0632e+00,  7.3154e-01],
        [ 1.2391e-01, -8.6092e-01,  2.2969e+00]], grad_fn=<EmbeddingBackward0>)


In [9]:
from torch import nn
class MyFirstModel(nn.Module):
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
    super(MyFirstModel, self).__init__()
    # Định nghĩa các lớp (layer) bạn sẽ dùng
    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.linear = nn.Linear(embedding_dim, hidden_dim)
    self.activation = nn.ReLU() # Hàm kích hoạt
    self.output_layer = nn.Linear(hidden_dim, output_dim)
  def forward(self, indices):
    # Định nghĩa luồng dữ liệu đi qua các lớp
    # 1. Lấy embedding
    embeds = self.embedding(indices)
    # 2. Truyền qua lớp linear và hàm kích hoạt
    hidden = self.activation(self.linear(embeds))
    # 3. Truyền qua lớp output
    output = self.output_layer(hidden)
    return output
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
